export const siteConfig = {
  name: "Aurora Beauty Studio",
  url: "https://aurora.zandeckidev.pl",
  creator: "Piotr Zandecki",
  email: "hello@aurorabeauty.pl",
  phone: "+48 123 456 789",
  phoneHref: "tel:+48123456789",
  instagramLabel: "@aurora.beauty",
  instagramUrl: "https://instagram.com",
  address: "ul. Różana 12, 00-001 Warszawa",
  shortAddressPl: "ul. Różana 12, Warszawa",
  shortAddressEn: "12 Różana Street, Warsaw",
  description:
    "Premium beauty studio offering facial care, brow and lash styling, and occasion makeup with a focus on natural results, calm atmosphere and refined client experience.",
  descriptionPl:
    "Premium beauty studio oferujące pielęgnację twarzy, stylizację brwi i rzęs oraz makijaż okazjonalny — z naciskiem na naturalny efekt, spokojną atmosferę i dopracowane doświadczenie klientki.",
  keywords: [
    "beauty studio",
    "salon beauty",
    "premium beauty studio",
    "kosmetologia",
    "pielęgnacja twarzy",
    "zabiegi na twarz",
    "stylizacja brwi",
    "stylizacja rzęs",
    "makijaż okazjonalny",
    "makijaż ślubny",
    "Warszawa",
  ],
};
